FROM baseimage

MAINTAINER Marc Rudolph <marc.a.rudolph@gmail.com>

VOLUME /cfg

ADD https://raw.githubusercontent.com/andreafabrizi/Dropbox-Uploader/master/dropbox_uploader.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/dropbox_uploader.sh
