FROM baseimage

MAINTAINER Marc Rudolph <marc.a.rudolph@gmail.com>

ADD https://iojs.org/dist/v1.0.1/iojs-v1.0.1-linux-x64.tar.xz /tmp/
RUN tar -xvf /tmp/iojs*.tar.xz --strip-components=1 -C /usr/local
